#!/bin/bash

alias getfortune='wget --timeout=3 -O - -q'
alias fortune='getfortune http://www.iheartquotes.com/api/v1/random'

FORTUNE=$(wget --timeout=3 -O - -q http://www.iheartquotes.com/api/v1/random)
echo "$FORTUNE" > ~/.motd/motd/last_fortune
NOHTTP=$(echo "$FORTUNE" | sed 's\&.*;\\g' 2>/dev/null | sed 's\http:.*\\g' 2>/dev/null)

#echo "$NOHTTP"

OUT=$(python ~/.motd/cowsay.py "$NOHTTP" 2>/dev/null)

if [ ! -z "$OUT" -a "$OUT" != " " ]; then
	echo "$OUT"
else
	echo -e "(Cowsay is not supported on this system... sorry.)\n\n $FORTUNE"
fi
